branches:
  except:
  - modern_cmake
language: cpp
dist: trusty
os:
  - linux
#  - osx
compiler:
- gcc
- clang
before_install:
  # - ( git clone -b devel https://github.com/AlloSphere-Research-Group/Gamma /tmp/Gamma )
  # - ( git clone -b cmake https://github.com/AlloSphere-Research-Group/GLV /tmp/GLV )
  # - ( git clone https://github.com/rbtsx/cuttlebone.git /tmp/cuttlebone )
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
addons:
  apt:
    sources:
    - sourceline: 'ppa:keithw/glfw3'
    - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
    - gcc-4.9
    - g++-4.9
    # - portaudio19-dev
    # - libsndfile1-dev
    - libglew-dev
    - libglfw3-dev
    - xorg-dev
    # - libglfw3-dev
    # - libusb-1.0-0-dev
    - libfreeimage-dev
    - libfreetype6-dev
    - libassimp-dev
    # - libluajit-5.1-dev
    # - libjsoncpp-dev
    # - libfftw3-dev
script:
    - cmake . -DTRAVIS_BUILD=1 -DBUILD_EXAMPLES=1 -DCMAKE_BUILD_TYPE=Debug\
    - make
    - make test
sudo: false
notifications:
  email:
    recipients:
    - mantaraya36@gmail.com
    - younkeehong@gmail.com
