# search in project folder, the dependencies manually put by user

if((NOT FREEIMAGE_LIBRARIES) OR (NOT FREEIMAGE_INCLUDE_DIRS))
  FIND_PATH(FREETIMAGELOCAL_INCLUDE_DIR FreeImage.h
    PATHS ${CMAKE_CURRENT_LIST_DIR}/../../windows/FreeImage/x32
    NO_DEFAULT_PATH
    NO_CMAKE_ENVIRONMENT_PATH
    NO_CMAKE_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_SYSTEM_PATH
    NO_CMAKE_FIND_ROOT_PATH
  )

  FIND_LIBRARY(FREEIMAGELOCAL_LIBRARY FreeImage
    PATHS ${CMAKE_CURRENT_LIST_DIR}/../../windows/FreeImage/x32
    NO_DEFAULT_PATH
    NO_PACKAGE_ROOT_PATH
    NO_CMAKE_PATH
    NO_CMAKE_ENVIRONMENT_PATH
    NO_SYSTEM_ENVIRONMENT_PATH
    NO_CMAKE_SYSTEM_PATH
    NO_CMAKE_FIND_ROOT_PATH
  )

  # set the user variables
  SET(FREEIMAGE_INCLUDE_DIRS ${FREEIMAGELOCAL_INCLUDE_DIR})
  SET(FREEIMAGE_LIBRARIES "${FREEIMAGELOCAL_LIBRARY}")

  INCLUDE(FindPackageHandleStandardArgs)
  FIND_PACKAGE_HANDLE_STANDARD_ARGS(FREEIMAGE DEFAULT_MSG  FREEIMAGE_LIBRARIES  FREEIMAGE_INCLUDE_DIRS)

  MARK_AS_ADVANCED(FREEIMAGELOCAL_LIBRARY FREEIMAGELOCAL_INCLUDE_DIR)

endif()
